In [1]:
import pandas as pd

In [2]:
mvps = pd.read_csv("mvps.csv")

In [3]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,10,11,Russell Westbrook,32,WAS,0.0,5.0,1010,0.005,65,...,11.5,11.7,1.4,0.4,0.439,0.315,0.656,3.7,0.075,2021
470,11,12,Ben Simmons,24,PHI,0.0,3.0,1010,0.003,58,...,7.2,6.9,1.6,0.6,0.557,0.300,0.613,6.0,0.153,2021
471,12,13T,James Harden,31,TOT,0.0,1.0,1010,0.001,44,...,7.9,10.8,1.2,0.8,0.466,0.362,0.861,7.0,0.208,2021
472,13,13T,LeBron James,36,LAL,0.0,1.0,1010,0.001,45,...,7.7,7.8,1.1,0.6,0.513,0.365,0.698,5.6,0.179,2021
473,14,13T,Kawhi Leonard,29,LAC,0.0,1.0,1010,0.001,52,...,6.5,5.2,1.6,0.4,0.512,0.398,0.885,8.8,0.238,2021

In [4]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [5]:
mvps.head()

            Player  Year  Pts Won  Pts Max  Share
0   Michael Jordan  1991    891.0      960  0.928
1    Magic Johnson  1991    497.0      960  0.518
2   David Robinson  1991    476.0      960  0.496
3  Charles Barkley  1991    222.0      960  0.231
4      Karl Malone  1991    142.0      960  0.148

In [6]:
players = pd.read_csv("players.csv")

In [7]:
players

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18039,725,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
18040,726,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
18041,727,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
18042,728,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
18043,729,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [8]:
del players["Unnamed: 0"]
del players["Rk"]

In [9]:
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [10]:
players["Player"] = players["Player"].str.replace("*", "", regex = False)

In [11]:
players["Player"].head(50)

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           Miloš Babić
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23       Charles Barkley
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
30       Benoit Benjamin
31       Benoit Benjamin
32       Benoit Benjamin
33       Winston Bennett
34            Larry Bird
35      Rolando Blackman
36          Lance Blanks
37       Mookie Blaylock
38         Muggsy Bogues
39            Manute Bol
40        Anthony Bonner
41             Sam Bowie
42          Randy Breuer
43      Frank Brickowski
44          Scott Brooks
45          Chucky Brown
46             Dee Brown
47                Player
48            Mike Brown
49            Tony Brown
Name: Player, dtype: object

In [12]:
players.groupby(["Player", "Year"])

In [13]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1, :]["Tm"]
        return row
    
players = players.groupby(["Player", "Year"]).apply(single_row)

In [14]:
players.head(20)

                                 Player Pos Age   Tm   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 164       A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6
              1992 633       A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8
              1993 1092      A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6
              1994 1579      A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3
              1995 2067      A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5
              1996 2563      A.C. Green  SF  32  PHO  82  36  25.8  2.6   5.4
              1997 3138      A.C. Green  PF  33  DAL  83  73  30.0  2.8   5.8
              1998 3725      A.C. Green  PF  34  DAL  82  68  32.3  3.0   6.5
              1999 4283      A.C. Green  PF  35  DAL  50  35  18.5  2.2   5.1
              2000 4811      A.C. Green  PF  36  LAL  82  82  23.5  2.1   4.7
              2001 5330      A.C. Green  PF  37  MIA  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 4684   A.J. Bramlett   C  23  CLE   8   0   7.6  0.5   2.6
A.J. English  1991 127     A.J. English  SG  23  WSB  70  12  20.6  3.6   8.2
              1992 597     A.J. English  SG  24  WSB  81   6  20.6  4.5  10.4
A.J. Guyton   2001 5333     A.J. Guyton  PG  22  CHI  33   8  19.1  2.4   5.8
              2002 5886     A.J. Guyton  PG  23  CHI  45   6  13.5  2.0   5.4
              2003 6393     A.J. Guyton  PG  24  GSW   2   0   4.5  0.0   2.0
A.J. Hammons  2017 14814   A.J. Hammons   C  24  DAL  22   0   7.4  0.8   1.9
A.J. Price    2010 10727     A.J. Price  PG  23  IND  56   2  15.4  2.6   6.3
              2011 11356     A.J. Price  PG  24  IND  50   0  15.9  2.3   6.4

                           FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player        Year              ...
A.C. Green    1991 164    .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 633    .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 1092   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 1579   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 2067   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 2563   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1997 3138   .483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9  1.7
              1998 3725   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 4283   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 4811   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 5330   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 4684   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 127    .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 597    .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Guyton   2001 5333   .406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7  1.1
              2002 5886   .361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8  0.5
              2003 6393   .000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5  0.0
A.J. Hammons  2017 14814  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6  0.5  1.0
A.J. Price    2010 10727  .410  ...  0.2  1.4  1.6  1.9  0.6  0.1  1.1  0.9
              2011 11356  .356  ...  0.3  1.1  1.4  2.2  0.6  0.0  1.1  1.2

                           PTS  Year
Player        Year
A.C. Green    1991 164     9.1  1991
              1992 633    13.6  1992
              1993 1092   12.8  1993
              1994 1579   14.7  1994
              1995 2067   11.2  1995
              1996 2563    7.5  1996
              1997 3138    7.2  1997
              1998 3725    7.3  1998
              1999 4283    4.9  1999
              2000 4811    5.0  2000
              2001 5330    4.5  2001
A.J. Bramlett 2000 4684    1.0  2000
A.J. English  1991 127     8.8  1991
              1992 597    10.9  1992
A.J. Guyton   2001 5333    6.0  2001
              2002 5886    5.4  2002
              2003 6393    0.0  2003
A.J. Hammons  2017 14814   2.2  2017
A.J. Price    2010 10727   7.3  2010
              2011 11356   6.5  2011

[20 rows x 30 columns]

In [15]:
players.index = players.index.droplevel()

In [16]:
players.index = players.index.droplevel()

In [17]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
467,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1412,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1911,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2381,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2948,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3541,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [18]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [19]:
combined.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [20]:
combined[combined["Pts Won"] > 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
187,Al Jefferson,C,29,CHA,73,73,35.0,9.6,18.8,.509,...,2.1,0.9,1.1,1.7,2.4,21.8,2014,34.0,1250.0,0.027
329,Allen Iverson,PG,21,PHI,76,74,40.1,8.2,19.8,.416,...,7.5,2.1,0.3,4.4,3.1,23.5,1997,1.0,1150.0,0.001
331,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,.412,...,4.6,2.3,0.1,3.5,2.0,26.8,1999,319.0,1180.0,0.270
332,Allen Iverson,SG,24,PHI,70,70,40.8,10.4,24.8,.421,...,4.7,2.1,0.1,3.3,2.3,28.4,2000,132.0,1210.0,0.109
333,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,.420,...,4.6,2.5,0.3,3.3,2.1,31.1,2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13587,Vince Carter,SF,23,TOR,82,82,38.1,9.6,20.7,.465,...,3.9,1.3,1.1,2.2,3.2,25.7,2000,51.0,1210.0,0.042
13588,Vince Carter,SF,24,TOR,75,75,39.7,10.2,22.1,.460,...,3.9,1.5,1.1,2.2,2.7,27.6,2001,7.0,1240.0,0.006
13592,Vince Carter,SF-SG,28,NJN,77,76,36.7,9.0,20.0,.452,...,4.2,1.4,0.6,2.2,3.2,24.5,2005,3.0,1270.0,0.002
13952,Yao Ming,C,23,HOU,82,82,32.8,6.5,12.5,.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
13957,Yao Ming,C,28,HOU,77,77,33.6,7.4,13.4,.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001

In [21]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14092 entries, 0 to 14091
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   14092 non-null  object
 1   Pos      14092 non-null  object
 2   Age      14092 non-null  object
 3   Tm       14092 non-null  object
 4   G        14092 non-null  object
 5   GS       14092 non-null  object
 6   MP       14092 non-null  object
 7   FG       14092 non-null  object
 8   FGA      14092 non-null  object
 9   FG%      14042 non-null  object
 10  3P       14092 non-null  object
 11  3PA      14092 non-null  object
 12  3P%      12050 non-null  object
 13  2P       14092 non-null  object
 14  2PA      14092 non-null  object
 15  2P%      14008 non-null  object
 16  eFG%     14042 non-null  object
 17  FT       14092 non-null  object
 18  FTA      14092 non-null  object
 19  FT%      13630 non-null  object
 20  ORB      14092 non-null  object
 21  DRB      14092 non-null  object
 22  TRB      14092 non-null  object
 23  AST      14092 non-null  object
 24  STL      14092 non-null  object
 25  BLK      14092 non-null  object
 26  TOV      14092 non-null  object
 27  PF       14092 non-null  object
 28  PTS      14092 non-null  object
 29  Year     14092 non-null  int64
 30  Pts Won  474 non-null    float64
 31  Pts Max  474 non-null    float64
 32  Share    474 non-null    float64
dtypes: float64(3), int64(1), object(29)
memory usage: 3.7+ MB

In [22]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [23]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
14088,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
14089,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
14090,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
14091,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [24]:
teams = pd.read_csv("teams.csv")

In [25]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team,Seed
0,7,61,21,0.744,—,110.0,101.0,8.57,1991,Chicago Bulls*,1
1,0,56,26,0.683,—,111.5,105.7,5.22,1991,Boston Celtics*,2
2,8,50,32,0.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*,3
3,9,48,34,0.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*,4
4,1,44,38,0.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*,5
5,10,43,39,0.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*,6
6,11,41,41,0.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*,7
7,2,39,43,0.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*,8
8,12,33,49,0.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers,9
9,3,30,52,0.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets,10
10,4,26,56,0.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets,11
11,13,26,56,0.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets,12
12,5,24,58,0.293,32.0,101.8,107.8,-5.91,1991,Miami Heat,13
13,9,63,19,0.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*,1
14,10,58,24,0.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*,2
15,1,55,27,0.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*,3
16,11,55,27,0.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*,4
17,2,54,28,0.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*,5
18,3,52,30,0.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*,6
19,12,44,38,0.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*,7
20,13,41,41,0.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*,8
21,4,31,51,0.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic,9
22,14,31,51,0.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers,10
23,5,29,53,0.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves,11
24,6,28,54,0.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks,12
25,15,25,57,0.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings,13
26,7,20,62,0.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets,14
27,8,67,15,0.817,—,109.9,99.5,10.07,1992,Chicago Bulls*,1
28,9,57,25,0.695,10.0,108.9,103.4,5.34,1992,Cleveland Cavaliers*,2
29,0,51,31,0.622,—,106.6,103.0,3.41,1992,Boston Celtics*,3

In [27]:
teams["Team"] = teams["Team"].str.replace("*", "", regex = False)

In [28]:
teams.head(5)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team,Seed
0,7,61,21,0.744,—,110.0,101.0,8.57,1991,Chicago Bulls,1
1,0,56,26,0.683,—,111.5,105.7,5.22,1991,Boston Celtics,2
2,8,50,32,0.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons,3
3,9,48,34,0.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks,4
4,1,44,38,0.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers,5

In [29]:
teams["Team"].unique()

array(['Chicago Bulls', 'Boston Celtics', 'Detroit Pistons',
       'Milwaukee Bucks', 'Philadelphia 76ers', 'Atlanta Hawks',
       'Indiana Pacers', 'New York Knicks', 'Cleveland Cavaliers',
       'Washington Bullets', 'New Jersey Nets', 'Charlotte Hornets',
       'Miami Heat', 'Portland Trail Blazers', 'Los Angeles Lakers',
       'San Antonio Spurs', 'Phoenix Suns', 'Utah Jazz',
       'Houston Rockets', 'Golden State Warriors', 'Seattle SuperSonics',
       'Orlando Magic', 'Los Angeles Clippers', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Sacramento Kings', 'Denver Nuggets',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [30]:
combined["Tm"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'DEN', 'ORL', 'NOH', 'TOR', 'SAC',
       'CHO', 'POR', 'DET', 'PHI', 'UTA', 'MIL', 'VAN', 'SEA', 'NJN',
       'NOK', 'LAC', 'OKC', 'ATL', 'CHA', 'MEM', 'NYK', 'NOP', 'BRK',
       'SAS', 'CHH'], dtype=object)

In [31]:
nicknames = {}
with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1: ]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

nicknames

{'ATL': 'Atlanta Hawks',
 'BRK': 'Brooklyn Nets',
 'BKN': 'Brooklyn Nets',
 'BOS': 'Boston Celtics',
 'CHA': 'Charlotte Bobcats',
 'CHH': 'Charlotte Hornets',
 'CHO': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls',
 'CLE': 'Cleveland Cavaliers',
 'DAL': 'Dallas Mavericks',
 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers',
 'LAL': 'Los Angeles Lakers',
 'MEM': 'Memphis Grizzlies',
 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks',
 'MIN': 'Minnesota Timberwolves',
 'NJN': 'New Jersey Nets',
 'NOH': 'New Orleans Hornets',
 'NOP': 'New Orleans Pelicans',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'NYK': 'New York Knicks',
 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic',
 'PHI': 'Philadelphia 76ers',
 'PHX': 'Phoenix Suns',
 'PHO': 'Phoenix Suns',
 'POR': 'Portland Trail Blazers',
 'SEA': 'Seattle SuperSonics',
 'SAC': 'Sacramento Kings',
 'SAS': 'San Antonio Spurs',
 'TOR': 'Toronto Raptors',
 'UTA': 'Utah Jazz',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'WSB': 'Washington Bullets'}

In [32]:
combined["Team"] = combined["Tm"].map(nicknames)

In [33]:
combined.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns

In [34]:
stats = combined.merge(teams, how="outer", on = ["Team", "Year"])

In [35]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Seed
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73,2
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73,2
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73,2
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73,2
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,Los Angeles Lakers,10,58,24,0.707,5.0,106.3,99.6,6.73,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,.484,...,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45,6
14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,.286,...,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45,6
14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,.470,...,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45,6
14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,.459,...,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45,6
14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,.455,...,Milwaukee Bucks,7,42,40,0.512,9.0,103.6,103.8,-0.45,6

In [36]:
del stats["Unnamed: 0"]

In [37]:
stats = stats.apply(pd.to_numeric, errors = "ignore")

In [38]:
stats.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
Seed         int64
dtype: object

In [39]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '—', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '1.0', '13.0', '17.0', '3.0', '15.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '50.0', '10.0', '30.0',
       '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '43.0', '39.0',
       '18.5', '48.0', '46.0', '10.5', '32.0', '38.0', '27.0', '33.0',
       '31.0', '21.5', '45.0', '22.5', '25.5', '3.5', '20.5', '11.5',
       '44.0', '52.0', '56.0', '2.5', '12.5', '47.0', '32.5', '4.5'],
      dtype=object)

In [40]:
stats["GB"] = stats["GB"].str.replace("—", "0")

In [41]:
stats["GB"] = pd.to_numeric(stats["GB"])

In [42]:
stats.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
Seed         int64
dtype: object

In [43]:
stats.to_csv("player_mvp_stats.csv")

In [ ]:
highest_scoring = stats[stats["G"] > 70].sort_values("PTS", ascending = False).head(10)

In [ ]:
highest_scoring.plot.bar("Player", "PTS")

In [ ]:
highest_scoring = stats.groupby("Year").apply(lambda x: x.sort_values("PTS", ascending = False).head(1))

In [ ]:
highest_scoring.plot.bar("Year", "PTS")

In [ ]:
stats.corr()["Share"]

In [ ]:
stats.corr()["Share"].plot.bar()